name: build linux
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM and Clang 17
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '17.0.4'
          env: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.27.x'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch -t src/deps

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        working-directory: src/

      - name: build
        run: cmake --build . --clean-first
        working-directory: src/

      - uses: actions/upload-artifact@v3
        with:
          name: Relay Daemon Linux Executable
          path: |
            src/lib/relay-daemon
